version: 2

models:
  - name: stg_weather
    columns:
      - name: time
        tests:
          - not_null
          - unique
      - name: temperature_2m
        tests:
          - not_null

  - name: stg_taxi_trips
    columns:
      - name: pickup_datetime
        tests:
          - not_null
      - name: dropoff_datetime
        tests:
          - not_null
      - name: pickup_location_id
        tests:
          - not_null

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
  - name: dim_zone
    columns:
      - name: location_id
        tests:
        - unique
        - not_null

  - name: fact_trips
    columns:
      - name: payment_type_id
        description: "Foreign key to the payment_type dimension table"
        tests:
        - not_null
        - relationships:
            arguments:
              to: ref('dim_payment_type')
              field: payment_type_id
      - name: pickup_location_id
        description: "Foreign key to the zone dimension table"
        tests:
        - not_null
        - relationships:
            arguments:
              to: ref('dim_zone')
              field: location_id
      - name: dropoff_location_id
        description: "Foreign key to the zone dimension table"
        tests:
        - not_null
        - relationships:
            arguments:
              to: ref('dim_zone')
              field: location_id

  - name: fact_weather
    columns:
    - name: time
      tests:
        - not_null
        - unique
    - name: temperature_2m
      tests:
        - not_null
    - name: precipitation
      tests:
        - not_null
    - name: windspeed_10m
      tests:
        - not_null
    - name: date_key
      tests:
        - not_null
        - relationships:
            arguments:
              to: ref('dim_date')
              field: date_key
